module.exports = {
  ERROR_UNHANDLED_REJECTION: 'ERROR_UNHANDLED_REJECTION',
  ERROR_UNCAUGHT_EXCEPTION: 'ERROR_UNCAUGHT_EXCEPTION',
  ERROR_HANDLED_ROUTE_ERROR: 'ERROR_HANDLED_ROUTE_ERROR',
  UNAUTHORIZED_IP_ACCESS: 'UNAUTHORIZED_IP_ACCESS',
};
